name: PR Code Check

on:
  pull_request:
    branches: [main]

jobs:
  code-style:
    uses: spacemit-robotics/scripts/.github/workflows/code-style-reusable.yml@main
    with:
      repo_path: components/multimedia/audio
